### PR TITLE
URA-241_processing : Function added to QDNAseq processing script

### PR DESCRIPTION
**Pull request by nadia31415**
Changes made : 
- Created separate function for segmented read counts plot
- Adjusted plot size
- Formatted comments

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @nadia31415)

___
*[`run_qdnaseq.Rmd` line 3 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_vx7qDK5ZLy7duilj:-NU_vx7qDK5ZLy7duilk:bgzp1x7) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L3)):*
> ```
> ---
> title: "run_me.Rmd"
> author: "Sophie Paul"
> ```

update author to East GLH ? Or something along those lines 
___
*[`run_qdnaseq.Rmd` line 4 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_w56yEcBhucB5Z793:-NU_w56yEcBhucB5Z794:b-pijpzv) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L4)):*
> ```
> title: "run_me.Rmd"
> author: "Sophie Paul"
> date: '2023-04-05'
> ```

remove date
___
*[`run_qdnaseq.Rmd` line 13 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_w8K91s29t_WWVPev:-NU_w8K91s29t_WWVPew:b-lgls6l) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L13)):*
> ```
> 
> ```{r}
> install.packages("tidyverse")
> ```

dont need to install it every time - can do if statement tidyverse is not available then install it
___
*[`run_qdnaseq.Rmd` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wQPtCXBQsgN-jzge:-NU_wQPtCXBQsgN-jzgf:b4m2xg6) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L32)):*
> ```
> 
> ```{r}
> bins <- getBinAnnotations(binSize=500, genome="hg38")
> ```

can the bin size be string for now, like the <BAM_PATH> so in the future the user sets it themselves
___
*[`run_qdnaseq.Rmd` line 49 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wdhKCaxloQXaGUM3:-NU_wdhKCaxloQXaGUM4:b4ywll3) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L49)):*
> ```
> #stabilise variance of a Poisson distribution 
> copy_Numbers_segmented <- readCounts %>%
>   applyFilters(residual=TRUE, blacklist=100) %>%
> ```

comment as to why 100 value was used
___
*[`run_qdnaseq.Rmd` line 91 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_x3vF9jGPONnyOxN3:-NU_x3vF9jGPONnyOxN4:b-qt4nph) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L91)):*
> ```
> 
> ```{r}
> png(width=1300, height=800)
> ```

add filename here 
___
*[`run_qdnaseq.Rmd` line 101 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_xkxxBWyzDn2mQkn3:-NU_xkxxBWyzDn2mQkn4:b-w8x9xh) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L101)):*
> ```
> ```{r}
> ## Summarised calls - one file per sample
> QDNAseq::exportBins(copyNumbersCalled, format = "seg", type = "calls", file = "%s.summarised_calls.tsv")
> ```

add information about bin used for this segment for the filename output
___
*[`run_qdnaseq.Rmd` line 103 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_xbIQBjlwoiySe6L-:-NU_xbIQBjlwoiySe6L0:b7wdo2p) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L103)):*
> ```
> QDNAseq::exportBins(copyNumbersCalled, format = "seg", type = "calls", file = "%s.summarised_calls.tsv")
> ## Raw calls - one file that contains *all* samples together
> QDNAseq::exportBins(copyNumbersCalled, format = "tsv", type = "calls", file = "all_calls_binsize_500_merged.raw_calls_all_depths.tsv")
> ```

you can use the bin_string you set earlier and concat it the filename output

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @Aisha-D)

___
*[`run_qdnaseq.Rmd` line 3 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_vx7qDK5ZLy7duilj:-NUa1CcA0OjDYATQlMnL:b-dw573f) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L3)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

update author to East GLH ? Or something along those lines 
</blockquote></details>

updated author
___
*[`run_qdnaseq.Rmd` line 4 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_w56yEcBhucB5Z793:-NUa1Hfm3XBCdtOPAxnN:b-896fix) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L4)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

remove date
</blockquote></details>

Done.
___
*[`run_qdnaseq.Rmd` line 13 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_w8K91s29t_WWVPev:-NUa22clAskWhmQ8AhFz:b5hcyet) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L13)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

dont need to install it every time - can do if statement tidyverse is not available then install it
</blockquote></details>

added if statement for tidyverse installation
___
*[`run_qdnaseq.Rmd` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wQPtCXBQsgN-jzge:-NUa3_qP0XB0zEj7ZT9j:bb6un1j) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L32)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can the bin size be string for now, like the <BAM_PATH> so in the future the user sets it themselves
</blockquote></details>

Done
___
*[`run_qdnaseq.Rmd` line 49 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wdhKCaxloQXaGUM3:-NUa3pHJ-_JQZmtqfsVj:b-896fix) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L49)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

comment as to why 100 value was used
</blockquote></details>

Done.
___
*[`run_qdnaseq.Rmd` line 91 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_x3vF9jGPONnyOxN3:-NUa5faC3tBlsSgcqoRC:b-v2hzud) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L91)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

add filename here 
</blockquote></details>

added file names for 2 png output files
___
*[`run_qdnaseq.Rmd` line 101 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_xkxxBWyzDn2mQkn3:-NUa5y6D6jVptnfp7Tq5:b-43aklw) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L101)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

add information about bin used for this segment for the filename output
</blockquote></details>

Done for both raw and summarised output files
___
*[`run_qdnaseq.Rmd` line 103 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_xbIQBjlwoiySe6L-:-NUa9rk-3ZH8CCQltRAM:bb6un1j) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L103)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

you can use the bin_string you set earlier and concat it the filename output
</blockquote></details>

Done

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @nadia31415)

___
*[`run_qdnaseq.Rmd` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wQPtCXBQsgN-jzge:-NV-QDeN3M-E4-NfwBJc:b-hynwuh) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L32)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Done
</blockquote></details>

where/how is the binsize value selected in this script?
___
*[`run_qdnaseq.Rmd` line 101 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_xkxxBWyzDn2mQkn3:-NV-Q1bIDipDcpr_qdzo:b-vo9ngj) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L101)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Done for both raw and summarised output files
</blockquote></details>

missing a close bracket at the end
___
*[`run_qdnaseq.Rmd` line 103 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_xbIQBjlwoiySe6L-:-NV-PxfO81t18oG-pg1c:b-ygiixx) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L103)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Done
</blockquote></details>

the paste is missing, correction below

file = paste("all_calls_binsize_",binsize,"_merged.raw_calls_all_depths.tsv", sep = "")_

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`run_qdnaseq.Rmd` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wQPtCXBQsgN-jzge:-NV-Rir86xF69uF2Ol6f:bhv0huh) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L32)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

where/how is the binsize value selected in this script?
</blockquote></details>

The binsize value comes from the bins function where there is an argument for user to set the value
___
*[`run_qdnaseq.Rmd` line 103 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_xbIQBjlwoiySe6L-:-NV-Sf9L7jDomyr6nqZu:belyc5q) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L103)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

the paste is missing, correction below

file = paste("all_calls_binsize_",binsize,"_merged.raw_calls_all_depths.tsv", sep = "")_
</blockquote></details>

paste added

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadia31415)

___
*[`run_qdnaseq.Rmd` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wQPtCXBQsgN-jzge:-NV-uJ7i00-YSFYrGrqQ:b45h) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L32)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

The binsize value comes from the bins function where there is an argument for user to set the value
</blockquote></details>





_Code snippet:_
```
bins <- function(binsize){
  getBinAnnotations(binSize=binsize, genome="hg38")
}
binsize <- "<binsize>"
readCounts <- binReadCounts(bins(binsize), path = "<BAM_PATH>")
```

**Review by nadia31415 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`run_qdnaseq.Rmd` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wQPtCXBQsgN-jzge:-NV006eg7-FDVfS4O1ps:b-7hm464) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L32)):*
> ```
> 
> ```{r}
> bins <- getBinAnnotations(binSize=500, genome="hg38")
> ```

Tried function after setting binsize variable but error generated, removing function and setting binsize before getting bins now works. Added comment on which bin sizes are avaiable for hg38



_Code snippet:_
```
Error in value[[3L]](cond) : 
  QDNAseq bin annotation ‘hg38.50kbp.50’ was not found in package ‘QDNAseq.hg38’. Available bin annotations are: ‘hg38.1000kbp.SR50’, ‘hg38.100kbp.SR50’, ‘hg38.10kbp.SR50’, ‘hg38.15kbp.SR50’, ‘hg38.1kbp.SR50’, ‘hg38.30kbp.SR50’, ‘hg38.500kbp.SR50’, ‘hg38.50kbp.SR50’, ‘hg38.5kbp.SR50’
```

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nadia31415)

___
*[`run_qdnaseq.Rmd` line 32 at r1](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2#-NU_wQPtCXBQsgN-jzge:-NV3wUMM2JBnieVIbDAa:bbk5m6g) ([raw file](https://github.com/eastgenomics/qdnaseq_cuh_glh/blob/48bf548ed64f48fc25ae4377b1fb14607008862a/run_qdnaseq.Rmd#L32)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Tried function after setting binsize variable but error generated, removing function and setting binsize before getting bins now works. Added comment on which bin sizes are avaiable for hg38
</blockquote></details>

well, thats a fun bug to find :)

**Review by Aisha-D — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/qdnaseq_cuh_glh/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nadia31415)

**Pull request merged**
